name: CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  GH_REGISTRY: ghcr.io
  GH_USERNAME: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 1
          - version: 2
          - version: 3

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ env.GH_USERNAME }}
          password: ${{ env.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}/version-${{ matrix.version }}"
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: web-application
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ matrix.version }}
